-- Create Database:
CREATE DATABASE "RestSampleDB";

-- Create Users Table:
CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Create Items Table:
CREATE TABLE "Items" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id")
);


-- Insert sample user into Users Table:
INSERT INTO "Users"(
	"Id", "Username", "Password")
	VALUES (1, "James", "$2a$11$kscuc/A4x.Pp/xhBHWNcBOLpkkaLKMQkA7JmXdm4HsGx9tykIhp7u");


-- Insert sample item into Items Table:
INSERT INTO "Items"(
	"Id", "Name", "Quantity")
	VALUES (1, "Clothes", 15);